apiVersion: autoscaling.containers.ai/v1alpha1
kind: AlamedaScaler
metadata:
  name: alamedaSelfDriving
  namespace: {{.NameSpace}}
spec:
  policy: stable
  enableExecution: true
  scalingTool:
    type: hpa
  selector:
    matchLabels:
      app: alameda
