apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller
  namespace: {{.NameSpace}}
  labels:
    app: alameda
    component: admission-controller
  annotations:
    description: Defines how to deploy the admission-controller
    template.alpha.openshift.io/wait-for-ready: 'true'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: admission-controller
  template:
    metadata:
      name: admission-controller
      labels:
        app: alameda
        component: admission-controller
    spec:
      containers:
      - name: admission-controller
        image: {{.Image.AdmissionController}}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 45m
            memory: 75Mi
        env:
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ALAMEDA_ADMCTL_DEPLOYEDNAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ALAMEDA_ADMCTL_DATAHUB_ADDRESS
          value: "alameda-datahub.{{.NameSpace}}.svc:50050"
        - name: ALAMEDA_ADMCTL_ENABLE
          value: 'true'
        - name: ALAMEDA_ADMCTL_TLSCERTFILE
          value: /etc/tls-certs/tls.crt
        - name: ALAMEDA_ADMCTL_TLSPRIVATEKEYFILE
          value: /etc/tls-certs/tls.key
        - name: ALAMEDA_ADMCTL_CACERTFILE
          value: /etc/tls-certs/ca.crt
        - name: ALAMEDA_ADMCTL_JSONPATCHVALIDATIONFUNC
          value: {{if eq .Platform "openshift3.9"}}"openshift3.9"{{else}}""{{end}}
        volumeMounts:
        - mountPath: /etc/tls-certs
          name: tls-certs
          readOnly: false
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/admission-controller
            - probe
            - --type=readiness
          failureThreshold: 20
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/admission-controller
            - probe
            - --type=liveness
          failureThreshold: 20
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 60
      {{if .NodeSelector}}
      nodeSelector:
        {{range $key, $value := .NodeSelector}}
          {{$key}}: {{$value}}
        {{end}}
      {{end}}
      volumes:
      - name:  admission-controller{{.VolumeNameSuffixes.Data}}
      - name:  admission-controller{{.VolumeNameSuffixes.Log}}
      - name: tls-certs
        secret:
          secretName: admission-controller-tls
      serviceAccount: admission-controller
      serviceAccountName: admission-controller
