apiVersion: apps/v1
kind: Deployment
metadata:
  name: alameda-ai
  namespace: {{.NameSpace}}
  labels:
    app: alameda
    component: alameda-ai
  annotations:
    description: Defines how to deploy the application alameda-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: alameda-ai
  template:
    metadata:
      name: alameda-ai
      labels:
        app: alameda
        component: alameda-ai
    spec:
      containers:
      - name: alameda-ai-engine
        ports:
            - containerPort: 9091
              name: ai-metrics
              protocol: TCP
        image: {{.Image.AIEngine}}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 2000m
            memory: 250Mi
        env:
        - name: OPERATOR_ADDRESS
          value: "alameda-operator.{{.NameSpace}}.svc:50050"
        - name: DATAHUB_ADDRESS
          value: "alameda-datahub.{{.NameSpace}}.svc:50050"
        - name: PREDICT_QUEUE_ENABLED
          value: {{if .AIDispatcher.Enabled}}"true"{{else}}"false"{{end}}
        - name: CONSUMER_PUSH_ENABLED
          value: "true"
        - name: PREDICT_QUEUE_URL
          value: "amqp://admin:adminpass@alameda-rabbitmq.{{.NameSpace}}.svc:5672"
        - name: MAXIMUM_PREDICT_PROCESSES
          value: "1"
        - name: MAXIMUM_MODEL_PROCESSES
          value: "3"
        - name: MAX_CPU_USAGE_PERCENTAGE
          value: "0.5"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        readinessProbe:
          exec:
            command:
            - /probe.sh
            - --type=readiness
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          exec:
            command:
            - /probe.sh
            - --type=liveness
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 60
        volumeMounts: 
        - name: alameda-ai-config
          mountPath: /alameda-ai/services/orchestra/workload_prediction/config
      {{if .NodeSelector}}
      nodeSelector:
        {{range $key, $value := .NodeSelector}}
          {{$key}}: {{$value}}
        {{end}}
      {{end}}
      volumes:
        - name: alameda-ai-config
          configMap:
            name: alameda-ai-config      
        - name: alameda-ai-data-storage
        - name: alameda-ai-log-storage
      serviceAccount: alameda-ai
      serviceAccountName: alameda-ai
