apiVersion: apps/v1
kind: Deployment
metadata:
  name: alameda-executor
  namespace: {{.NameSpace}}
  labels:
    app: alameda
    component: alameda-executor
spec:
  selector:
    matchLabels:
      component: alameda-executor
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alameda
        component: alameda-executor
    spec:
      serviceAccountName: alameda-executor
      containers:
      - name: alameda-executor
        image: {{.Image.Executor}}
        imagePullPolicy: Always
        volumeMounts:
          - name: alameda-executor-config
            mountPath: /etc/alameda/federatorai-execution/config.toml
            subPath: config.toml
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/federatorai-executor
            - probe
            - --type=readiness
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/federatorai-executor
            - probe
            - --type=liveness
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 60
      {{if .NodeSelector}}
      nodeSelector:
        {{range $key, $value := .NodeSelector}}
          {{$key}}: {{$value}}
        {{end}}
      {{end}}
      volumes:
        - name: alameda-executor-data-storage
        - name: alameda-executor-log-storage
        - name: alameda-executor-config
          configMap:
            name: alameda-executor-config
