apiVersion: apps/v1
kind: Deployment
metadata:
  name: alameda-ai-dispatcher
  namespace: {{.NameSpace}}
  labels:
    app: alameda
    component: alameda-ai-dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alameda
      component: alameda-ai-dispatcher
  template:
    metadata:
      labels:
        app: alameda
        component: alameda-ai-dispatcher
    spec:
      containers:
        - name: ai-dispatcher
          ports:
            - containerPort: 9091
              name: metrics
              protocol: TCP
          image: {{.Image.AIDispatcher}}
          imagePullPolicy: IfNotPresent
          env:
            - name: ALAMEDA_AI_DISPATCHER_DATAHUB_ADDRESS
              value: "alameda-datahub.{{.NameSpace}}.svc:50050"
            - name: ALAMEDA_AI_DISPATCHER_QUEUE_URL
              value: "amqp://admin:adminpass@alameda-rabbitmq.{{.NameSpace}}.svc:5672"
            - name: ALAMEDA_AI_DISPATCHER_MODEL_ENABLED
              value: "true"
          resources:
            {}
          readinessProbe:
            exec:
              command:
              - /usr/local/bin/ai-dispatcher
              - probe
              - --type=readiness
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 60
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/ai-dispatcher
              - probe
              - --type=liveness
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 60
          volumeMounts: 
          - name: alameda-ai-dispatcher-config
            mountPath: /etc/alameda/ai-dispatcher/ai-dispatcher.toml
            subPath: ai-dispatcher.toml
      {{if .NodeSelector}}
      nodeSelector:
        {{range $key, $value := .NodeSelector}}
          {{$key}}: {{$value}}
        {{end}}
      {{end}}
      volumes:
        - name: alameda-ai-dispatcher-config
          configMap:
            name: alameda-ai-dispatcher-config
        - name:  alameda-dispatcher{{.VolumeNameSuffixes.Data}}
        - name:  alameda-dispatcher{{.VolumeNameSuffixes.Log}}
