apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alameda
    component: alameda-notifier
  name: alameda-notifier  
  namespace: {{.NameSpace}}  
spec:
  serviceAccountName: alameda-notifier
  replicas: 1
  selector:
    matchLabels:
      app: alameda
      component: alameda-notifier
  template:
    metadata:
      labels:
        app: alameda
        component: alameda-notifier
    spec:
      containers:
      - name: alameda-notifier
        image: {{.Image.Notifier}}
        env:
          - name: NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ALAMEDA_NOTIFIER_DATAHUB_ADDRESS
            value: "alameda-datahub.{{.NameSpace}}.svc:50050"
          - name: ALAMEDA_NOTIFIER_RABBITMQ_URL
            value: "amqp://admin:adminpass@alameda-rabbitmq.{{.NameSpace}}.svc:5672"
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/notifier              
            - --readiness-probe              
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/notifier              
            - --liveness-probe              
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 60
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      serviceAccount: alameda-notifier
      {{if .NodeSelector}}
      nodeSelector:
        {{range $key, $value := .NodeSelector}}
          {{$key}}: {{$value}}
        {{end}}
      {{end}}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: alameda-notifier-webhook-server-cert
      - name: alameda-notifier-data-storage
      - name: alameda-notifier-log-storage
