apiVersion: apps/v1
kind: Deployment
metadata:
  name: federatorai-agent-app
  namespace: {{.NameSpace}}
  labels:
    app: alameda
    component: federatorai-agent-app
spec:
  selector:
    matchLabels:
      app: alameda
      component: federatorai-agent-app
  replicas: 1
  template:
    metadata:
      labels:
        app: alameda
        component: federatorai-agent-app
    spec:
      containers:
      - name: federatorai-agent-app
        image: {{.Image.FederatoraiAgentApp}}
        imagePullPolicy: Always
        volumeMounts:
        - name: federatorai-agent-app-config
          mountPath: /etc/alameda/federatorai-agent/transmitter.toml
          subPath: transmitter.toml
        - name: federatorai-agent-app-config
          mountPath: /etc/alameda/federatorai-agent/input/alameda_app.toml
          subPath: alameda_app.toml
        - name: federatorai-agent-app-config
          mountPath: /etc/alameda/federatorai-agent/input/alameda_node.toml
          subPath: alameda_node.toml
        - name: federatorai-agent-app-config
          mountPath: /etc/alameda/federatorai-agent/input/alameda_kafka.toml
          subPath: alameda_kafka.toml
        - mountPath: /etc/alameda/federatorai-agent/input/kubernetes.toml
          name: federatorai-agent-app-config
          subPath: kubernetes.toml
        - name: federatorai-agent-app-config
          mountPath: /etc/alameda/federatorai-agent/output/alameda_datahub.toml
          subPath: alameda_datahub.toml
        livenessProbe:
          exec:
            command:
            - /opt/alameda/federatorai-agent/bin/transmitter
            - probe
            - --type=liveness
          failureThreshold: 20
          initialDelaySeconds: 5
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 60
        readinessProbe:
          exec:
            command:
            - /opt/alameda/federatorai-agent/bin/transmitter
            - probe
            - --type=readiness
          failureThreshold: 20
          initialDelaySeconds: 5
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 60
      {{if .NodeSelector}}
      nodeSelector:
        {{range $key, $value := .NodeSelector}}
          {{$key}}: {{$value}}
        {{end}}
      {{end}}
      volumes:
      - name: federatorai-agent-app-config
        configMap:
          name: federatorai-agent-app-config
        items:
          - key: transmitter.toml
            path: transmitter.toml
          - key: alameda_app.toml
            path: alameda_app.toml
          - key: alameda_kafka.toml
            path: alameda_kafka.toml
          - key: alameda_datahub.toml
            path: alameda_datahub.toml
          - key: alameda_node.toml
            path: alameda_node.toml
      - name: federatorai-agent-app{{.VolumeNameSuffixes.Data}}
      - name: federatorai-agent-app{{.VolumeNameSuffixes.Log}}
      serviceAccount: federatorai-agent-app
      serviceAccountName: federatorai-agent-app