apiVersion: apps/v1
kind: Deployment
metadata:
  name: federatorai-rest
  namespace: {{.NameSpace}}
  labels:
    app: alameda
    component: federatorai-rest
  annotations:
    description: Defines how to deploy the application federatorai-rest
    template.alpha.openshift.io/wait-for-ready: 'true'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: federatorai-rest
  template:
    metadata:
      name: federatorai-rest
      labels:
        app: alameda
        component: federatorai-rest
    spec:
      containers:
      - name: federatorai-rest
        image: {{.Image.FederatoraiRestAPI}}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 45m
            memory: 75Mi
        env:
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INFLUXDB_ADDRESS
          value: https://alameda-influxdb.{{.NameSpace}}.svc:8086
        - name: INFLUXDB_USERNAME
          value: admin
        - name: INFLUXDB_PASSWORD
          value: adminpass
        - name: DATAHUB_ADDRESS
          value: alameda-datahub.{{.NameSpace}}.svc:50050
        - name: BINDADDRESS
          value: ":5055"
        readinessProbe:
          exec:
            command:
            - /init.sh
            - readiness
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          exec:
            command:
            - /init.sh
            - liveness
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 60
      {{if .NodeSelector}}
      nodeSelector:
        {{range $key, $value := .NodeSelector}}
          {{$key}}: {{$value}}
        {{end}}
      {{end}}
      volumes:
      - name:  federatorai-rest-data-storage
      - name:  federatorai-rest-log-storage
      serviceAccount: federatorai-rest
      serviceAccountName: federatorai-rest
