apiVersion: apps/v1
kind: Deployment
metadata:
  name: federatorai-agent
  namespace: {{.NameSpace}}
  labels:
    app: alameda
    component: federatorai-agent
spec:
  selector:
    matchLabels:
      app: federatorai-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: federatorai-agent
    spec:
      containers:
      - name: federatorai-agent
        image: {{.Image.FederatoraiAgent}}
        imagePullPolicy: Always
        volumeMounts:
          - name: federatorai-agent-config
            mountPath: /etc/alameda/federatorai-agent/transmitter.toml
            subPath: transmitter.toml
          - name: federatorai-agent-config
            mountPath: /etc/alameda/federatorai-agent/input/cost_analysis_daily.toml
            subPath: cost_analysis_daily.toml
          - name: federatorai-agent-config
            mountPath: /etc/alameda/federatorai-agent/input/cost_analysis_weekly.toml
            subPath: cost_analysis_weekly.toml
          - name: federatorai-agent-config
            mountPath: /etc/alameda/federatorai-agent/input/cost_analysis_monthly.toml
            subPath: cost_analysis_monthly.toml
        livenessProbe:
          exec:
            command:
              - /opt/alameda/federatorai-agent/bin/transmitter
              - probe
              - --type=liveness
          failureThreshold: 20
          initialDelaySeconds: 5
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 60
        readinessProbe:
          exec:
            command:
              - /opt/alameda/federatorai-agent/bin/transmitter
              - probe
              - --type=readiness
          failureThreshold: 20
          initialDelaySeconds: 5
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 60
      {{if .NodeSelector}}
      nodeSelector:
        {{range $key, $value := .NodeSelector}}
          {{$key}}: {{$value}}
        {{end}}
      {{end}}
      volumes:
      - name: federatorai-agent-config
        configMap:
          name: federatorai-agent-config
      - name: federatorai-agent{{.VolumeNameSuffixes.Data}}
      - name: federatorai-agent{{.VolumeNameSuffixes.Log}}
