apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedemeter-api
  namespace: {{.NameSpace}}
  labels:
    app: alameda
    component: fedemeter-api
spec:
  selector:
    matchLabels:
      app : fedemeter-api
  template:
      metadata:
        labels:
          app: fedemeter-api
      spec:
        containers:
        - name: fedemeter-api
          image: {{.Image.FedemeterAPI}}
          imagePullPolicy: Always
          ports:
          - name: gui-fedemeter
            containerPort: 8888
          tty:  true
          envFrom:
            - configMapRef:
                name: fedemeter-config
        volumes:
        - name: fedemeter{{.VolumeNameSuffixes.Data}}
        - name: fedemeter{{.VolumeNameSuffixes.Log}}
        serviceAccount: fedemeter-api
        serviceAccountName: fedemeter-api
