apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.NameSpace}}-alameda-operator
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  - statefulsets
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedascalers
  - alamedarecommendations
  - alamedamachinegroupscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedascalers/finalizers
  verbs:
  - update
# Permission for query prometheus under namespace openshift-monitoring
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - watch
  - list
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - watch
  - create
  - update
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - watch
  - create
  - update
  - list
  - delete
- verbs:
  - create
  - update
  apiGroups:
  - ""
  resources:
  - configmaps
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - machine.openshift.io
  resources:
  - machinesets
  - machines
  verbs:
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use