apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{.NameSpace}}-federatorai-data-adapter
rules:
- apiGroups:
    - ""
  resources:
  - namespaces
  - configmaps
  verbs:
  - get
