apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.NameSpace}}-federatorai-agent-app
rules:
# Permission for query prometheus under namespace openshift-monitoring
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
- apiGroups:
    - policy
  resources:
    - podsecuritypolicies
  verbs:
    - use
