apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.NameSpace}}-federatorai-rest
rules:
# Permission for query prometheus under namespace openshift-monitoring
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedascalers
  verbs:
  - get
  - list
  - create
  - delete
