apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.NameSpace}}-federatorai-agent
rules:
# Permission for query prometheus under namespace openshift-monitoring
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use