gcClusterRole = "alameda-gc"

[requirements]

[metrics]
port = 8383

[log]
outputLevel = "info" # one of 'debug', 'info', 'warn', 'error' (default info)
outputPaths = ["stdout", "/var/log/alameda/federatorai-operator.log"]

[grpc]
  [grpc.log]
  outputLevel = "info" # one of 'debug', 'info', 'warn', 'error' (default info)
  outputPaths = []

[patch]
  [patch.prometheus]
    [patch.prometheus.config]
    configMapName = "prometheus-k8s"
    secretName = "prometheus-k8s"

    [[patch.prometheus.metricRelabeling]]
    sourceLabels = ["container"]
    separator = ";"
    regex = "(.+)"
    targetLabel = "container_name"
    replacement = "$1"
    action = "replace"

    [[patch.prometheus.metricRelabeling]]
    sourceLabels = ["pod"]
    separator = ";"
    regex = "(.+)"
    targetLabel = "pod_name"
    replacement = "$1"
    action = "replace"