apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.NameSpace}}-alameda-recommender
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.NameSpace}}-alameda-recommender
subjects:
- kind: ServiceAccount
  name: alameda-recommender
  namespace: {{.NameSpace}}