apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.NameSpace}}-federatorai-agent-preloader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.NameSpace}}-federatorai-agent-preloader
subjects:
- kind: ServiceAccount
  name: federatorai-agent-preloader
  namespace: {{.NameSpace}}