apiVersion: apps/v1
kind: Deployment
metadata:
  name: federatorai-operator
  namespace: federatorai
  labels:
    name: federatorai-operator
    app: Federator.ai
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: federatorai-operator
  template:
    metadata:
      labels:
        name: federatorai-operator
        app: Federator.ai
    spec:
      serviceAccountName: federatorai-operator
      initContainers:
        - name: upgrader
          image: quay.io/prophetstor/federatorai-operator-ubi:latest
          command:
          - federatorai-operator
          args:
          - "upgrade"
          - "influxdb"
          volumeMounts:
          - mountPath: /var/log/alameda
            name: log
      containers:
        - name: federatorai-operator
          # Replace this with the built image name
          image: quay.io/prophetstor/federatorai-operator-ubi:latest
          imagePullPolicy: Always
          command:
          - federatorai-operator
          env:
            - name: NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
#            - name: FEDERATORAI_OPERATOR_WATCH_NAMESPACE
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "federatorai-operator"
            - name: DISABLE_OPERAND_RESOURCE_PROTECTION
              value: "true" 
            - name: RELATED_IMAGE_ADMISSION_CONTROLLER
              value: registry.connect.redhat.com/prophetstor/alameda-admission-ubi:latest
            - name: RELATED_IMAGE_AI_DISPATCHER
              value: registry.connect.redhat.com/prophetstor/alameda-ai-dispatcher:latest
            - name: RELATED_IMAGE_AI_ENGINE
              value: registry.connect.redhat.com/prophetstor/alameda-ai:latest
            - name: RELATED_IMAGE_ALPINE
              value: registry.connect.redhat.com/prophetstor/federatorai-tool:v0.9.6
            - name: RELATED_IMAGE_ANALYZER
              value: registry.connect.redhat.com/prophetstor/alameda-analyzer-ubi:latest
            - name: RELATED_IMAGE_DATAHUB
              value: registry.connect.redhat.com/prophetstor/alameda-datahub-ubi:latest
            - name: RELATED_IMAGE_EVICTIONER
              value: registry.connect.redhat.com/prophetstor/alameda-evictioner-ubi:latest
            - name: RELATED_IMAGE_EXECUTOR
              value: registry.connect.redhat.com/prophetstor/alameda-executor-ubi:latest
            - name: RELATED_IMAGE_FEDEMETER_API
              value: registry.connect.redhat.com/prophetstor/fedemeter-api-ubi:latest
            - name: RELATED_IMAGE_FEDEMETER_INFLUXDB
              value: registry.connect.redhat.com/prophetstor/fedemeter-influxdb:latest
            - name: RELATED_IMAGE_FEDERATORAI_AGENT
              value: registry.connect.redhat.com/prophetstor/federatorai-agent-ubi:latest
            - name: RELATED_IMAGE_FEDERATORAI_AGENT_GPU
              value: registry.connect.redhat.com/prophetstor/federatorai-agent-gpu:latest
            - name: RELATED_IMAGE_FEDERATORAI_AGENT_PRELOADER
              value: registry.connect.redhat.com/prophetstor/federatorai-agent-preloader:latest
            - name: RELATED_IMAGE_FEDERATORAI_RESTAPI
              value: registry.connect.redhat.com/prophetstor/federatorai-rest-ubi:latest
            - name: RELATED_IMAGE_GRAFANA
              value: registry.connect.redhat.com/prophetstor/alameda-grafana:latest
            - name: RELATED_IMAGE_INFLUXDB
              value: registry.connect.redhat.com/prophetstor/alameda-influxdb:latest
            - name: RELATED_IMAGE_NOTIFIER
              value: registry.connect.redhat.com/prophetstor/alameda-notifier-ubi:latest
            - name: RELATED_IMAGE_OPERATOR
              value: registry.connect.redhat.com/prophetstor/alameda-operator-ubi:latest
            - name: RELATED_IMAGE_RABBITMQ
              value: registry.connect.redhat.com/prophetstor/alameda-rabbitmq:latest
            - name: RELATED_IMAGE_RECOMMENDER
              value: registry.connect.redhat.com/prophetstor/alameda-recommender-ubi:latest
          volumeMounts:
          - mountPath: /var/log/alameda
            name: log
      volumes:
        - name: log
          emptyDir: {}
