apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alameda-recommender-data.pvc
  namespace: {{.NameSpace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi