apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: federatorai-agent-app-log.pvc
  namespace: {{.NameSpace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi