apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-federatorai-data-adapter-log
  namespace: {{.NameSpace}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
