apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fedemeter-influxdb-data.pvc
  namespace: {{.NameSpace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '10Gi'