apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: federatorai-data-adapter-data.pvc
  namespace: {{.NameSpace}}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
