apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-alameda.influxdb-data.pvc
  namespace: {{.NameSpace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '10Gi'