rule_files:
- /tmp/alameda-metric.rule
scrape_configs:
- job_name: kubernetes-nodes-cadvisor
  metric_relabel_configs:
  - source_labels: [container]
    separator: ;
    regex: (.+)
    target_label: container_name
    replacement: $1
    action: replace
  - source_labels: [pod]
    separator: ;
    regex: (.+)
    target_label: pod_name
    replacement: $1
    action: replace
- job_name: kubernetes-service-endpoints
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: alameda_label_pod
    replacement: $1
    action: replace
  metric_relabel_configs:
  - source_labels: [namespace, kubernetes_namespace]
    separator: ;
    regex: ;?([^;]*);?.*
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [node, kubernetes_node]
    separator: ;
    regex: ;?([^;]*);?.*
    target_label: node
    replacement: $1
    action: replace
  - source_labels: [pod, alameda_label_pod]
    separator: ;
    regex: ;?([^;]*);?.*
    target_label: pod
    replacement: $1
    action: replace
