apiVersion: v1
kind: ConfigMap
metadata:
  name: alameda-executor-config
  namespace: {{.NameSpace}}
data:
  config.toml: |-
    [datahub]
    address = "alameda-datahub.{{.NameSpace}}.svc"
    port = 50050
      [datahub.schemas]
        [datahub.schemas.recommendations]
          [datahub.schemas.recommendations.kafkaConsumerGroup]
          category = "kafka"
          type = "consumer_group"

    [executor]
    check-cycle = 3 # second
    expire-time = 300 # second
    enable = true

    [gRPC]
      [gRPC.log]
      outputLevel = "warn"