apiVersion: v1
kind: ConfigMap
metadata:
  name: alameda-recommender-config
  namespace: {{.NameSpace}}
data:
  config.toml: |-
    [global]
    hpa_interval = 180
    vpa_short_interval = 300
    vpa_long_interval = 3600
    debug = false

    [datahub]
    address = "alameda-datahub.{{.NameSpace}}.svc"
    port = 50050

    [fedemeter]
    enabled = false
    address = "fedemeter-api.{{.NameSpace}}.svc"
    port = 8888

    [hpa_scaling]
    alpha = 0.25
    k8s_threshold = 0.8
    limits_threshold = 0.9
    sample_rate = 15
    period_rate = 60
    period_count = 5
    data_source = "workload"

    [kafka]
    terminating_time = 30
    algo_interval = 60
    resource_tolerance = 0.25
    [kafka.weight]
    cpu = 0.031611
    memory = 0.004267
    io = 0.02411265         # MIOPS, aws oregon 0.0625/720/3600*1000000
    storage = 0.000111111   # gcp us-west local SSD GB
    request = 0.000005      # aws s3 oregon