apiVersion: v1
kind: ConfigMap
metadata:
  name: alameda-recommender-config
  namespace: {{.NameSpace}}
data:
  config.toml: |-
    [global]
    hpa_interval = 180
    vpa_short_interval = 300
    vpa_long_interval = 3600
    debug = false

    [datahub]
    address = "alameda-datahub.{{.NameSpace}}.svc"
    port = 50050

    [fedemeter]
    enabled = false
    address = "fedemeter-api.{{.NameSpace}}.svc"
    port = 8888

    [hpa_scaling]
    alpha = 0.25
    k8s_threshold = 0.8
    limits_threshold = 0.9
    sample_rate = 15
    period_rate = 60
    period_count = 5
    data_source = "workload"

    [nginx]
    margin = 0.2
    observation_granularity_seconds = 60
    observation_period_seconds = 60
    upper_resource_tolerance = 2
    lower_resource_tolerance = 0.5
    evaluation_type = "moving-avg"
    moving_average_period_seconds = 60
    shift_best_execution_time_seconds = 0
    historical_replica_capacity_period_seconds = 300

    [kafka]
    terminating_time = 30
    algo_interval = 60
    upper_resource_tolerance = -0.2
    lower_resource_tolerance = 0
    replica_scaling_tolerance = 0.1
    prediction_resource_tolerance = 0
    current_lag_threshold = 0
    qos_threshold = 0
    [kafka.weight]
    cpu = 0
    memory = 0
    storage = 0
    scaling_up = 0
    scaling_down = 200
    queue = 1
    [kafka.policy]
    cost_selection_max = true
    shift_best_execution_time_seconds = 0
    scaling_down_percent = 1
    [kafka.prediction]
    prediction_shift_start_seconds = 0
    prediction_shift_total_seconds = 300