apiVersion: v1
kind: ConfigMap
metadata:
  name: alameda-recommender-config
  namespace: {{.NameSpace}}
data:
  config.toml: |-
    [global]
    ca_interval = 180
    hpa_interval = 180
    vpa_short_interval = 300
    vpa_long_interval = 3600
    debug = false

    [datahub]
    address = "alameda-datahub.{{.NameSpace}}.svc"
    port = 50050

    [ca]
    prediction_granularity_seconds = 180
    prediction_shift_start_seconds = 0
    prediction_shift_total_seconds = 3600

    [fedemeter]
    enabled = false
    address = "fedemeter-api.{{.NameSpace}}.svc"
    port = 8888

    [hpa_scaling]
    alpha = 0.25
    k8s_threshold = 0.8
    limits_threshold = 0.9
    sample_rate = 15
    period_rate = 60
    period_count = 5
    data_source = "workload"

    [nginx]
    margin = 0.2
    observation_granularity_seconds = 60
    observation_period_seconds = 300
    max_upscale_ratio = 2.0
    max_downscale_ratio = 0.5
    ratio_to_inc_alpha = 1.5
    ratio_to_dec_alpha = 0.5
    upper_ratio_to_count_replica_capacity = 1.1
    lower_ratio_to_count_replica_capacity = 0.8
    evaluation_type = "moving-avg"
    moving_average_period_seconds = 60
    shift_best_execution_time_seconds = 0
    historical_replica_capacity_period_seconds = 300
    beta = 0
    initial_none_zero_count = 3
    replicas_capacity_resize_percentage = 1.0

    [kafka]
    terminating_time = 30
    algo_interval = 60
    upper_resource_tolerance = 0
    lower_resource_tolerance = 0
    replica_scaling_tolerance = 0
    prediction_resource_tolerance = 0
    current_lag_threshold = 0.2
    qos_threshold = 0
    alpha = 0.9
    beta = 0.9
    gamma = 0.1
    log_weight = 0

    [kafka.weight]
    cpu = 0
    memory = 0
    storage = 0
    scaling_up = 0
    scaling_down = 0
    queue = 0
    [kafka.policy]
    cost_selection_max = true
    shift_best_execution_time_seconds = 0
    scaling_down_percent = 0.9
    [kafka.prediction]
    prediction_shift_start_seconds = 0
    prediction_shift_total_seconds = 300