apiVersion: v1
kind: ConfigMap
metadata:
  name: alameda-recommender-config
  namespace: {{.NameSpace}}
data:
  config.toml: |-
    [global]
    hpa_interval = 180
    vpa_short_interval = 300
    vpa_long_interval = 3600
    debug = false

    [datahub]
    address = "alameda-datahub.{{.NameSpace}}.svc"
    port = 50050

    [fedemeter]
    enabled = false
    address = "fedemeter-api.{{.NameSpace}}.svc"
    port = 8888

    [hpa_scaling]
    alpha = 0.25
    k8s_threshold = 0.8
    limits_threshold = 0.9
    sample_rate = 15
    period_rate = 60
    period_count = 5
    data_source = "workload"

    [kafka]
    terminating_time = 30
    algo_interval = 60
    upper_resource_tolerance = 0
    lower_resource_tolerance = 0
    qos_threshold = 5
    [kafka.weight]
    cpu = 0
    memory = 0
    storage = 0
    scaling_up_weight = 1
    scaling_down_weight = 2
    scaling_down_speed = 300
